server:
    name: GOST Server
    host:
    port: 8080
    externalUri: http://localhost:8080/
    maxEntityResponse: 20
    indentedJson: true
    https: false
    httpsCert:
    httpsKey:
database:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: gost
    schema: v1
    ssl: false
    maxIdleConns: 30
    maxOpenConns: 100
mqtt:
    enabled: true
    host: localhost
    port: 1883
logger:
    fileName: gost
    verbose: true
 