version: '2'
services:
    gost-db:
        image: geodan/gost-db
        volumes:
            - postgis:/var/lib/pgsql/9.5/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    gost:
        image: geodan/gost
        ports:
            - "8080:8080"
        depends_on:
            - mosquitto
            - gost-db
        environment:
            gost_db_host: gost-db
volumes:
    postgis: {}
